export const LANGS = ["es", "en"] as const;
export type Lang = (typeof LANGS)[number];
export type Localized<T = string> = Record<Lang, T>;

export const DEFAULT_LANG: Lang = "en";

export function isLang(value: unknown): value is Lang {
  return typeof value === "string" && (LANGS as readonly string[]).includes(value);
}

/** Idioma a partir del primer segmento de la URL. Sirve también para la 404 (`/es/no-existe`). */
export function langFromPath(pathname: string): Lang | null {
  const first = pathname.split("/")[1];
  return isLang(first) ? first : null;
}

export function otherLang(lang: Lang): Lang {
  return lang === "es" ? "en" : "es";
}

export const messages = {
  es: {
    role: "Ingeniero de software",
    nav: { home: "Inicio", work: "Casos de estudio", cyberOps: "Cyber Ops" },
    skip: "Saltar al contenido",
    switchTo: "English",
    homeIntro:
      "Página de prueba del spike D4. Este texto existe en el HTML estático antes de que cargue JavaScript.",
    workTitle: "Casos de estudio",
    workIntro: "Índice generado desde un loader que se ejecuta en el build.",
    readCase: (t: string) => `Leer el caso ${t}`,
    cyberTitle: "Cyber Ops: un juego de seguridad",
    cyberIntro: "La lógica del juego vive en un chunk que solo pide esta ruta.",
    notFoundTitle: "Página no encontrada",
    notFoundBody: "Esta dirección no existe. Puedes volver al inicio o revisar los casos de estudio.",
    theme: "Cambiar tema",
  },
  en: {
    role: "Software engineer",
    nav: { home: "Home", work: "Case studies", cyberOps: "Cyber Ops" },
    skip: "Skip to content",
    switchTo: "Español",
    homeIntro:
      "Test page for spike D4. This text is in the static HTML before any JavaScript loads.",
    workTitle: "Case studies",
    workIntro: "Index generated by a loader that runs at build time.",
    readCase: (t: string) => `Read the ${t} case`,
    cyberTitle: "Cyber Ops: a security game",
    cyberIntro: "The game logic lives in a chunk that only this route requests.",
    notFoundTitle: "Page not found",
    notFoundBody: "This address does not exist. Go back home or browse the case studies.",
    theme: "Toggle theme",
  },
} as const;
